"""
WeWriteCore bootstrap utility.

Bridges VCP plugin environment (env vars + stdin JSON args) to the
unmodified `wewrite/` source tree shipped in this directory.

Responsibilities:
  1. Locate the embedded `wewrite/` skill root.
  2. Render `wewrite/config.yaml` and `wewrite/style.yaml` from VCP env
     vars, so that wewrite's CLI and scripts behave as if a user had
     run the upstream onboarding flow.
  3. Provide helpers for spawning wewrite scripts and for resolving
     remote `file://` URLs via VCP hyper-stack-trace.

This module is imported by every WeWrite* plugin (WeWriteRender,
WeWritePublish, WeWriteThemes, ...). It is NOT a standalone plugin
itself (no plugin-manifest.json).

The embedded wewrite source is treated as read-only: bootstrap only
writes the generated *.yaml configs into the wewrite root. Everything
else is left untouched so `git pull` upstream stays trivial.
"""

from __future__ import annotations

import base64
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any, Iterable
from urllib.parse import urlparse, unquote
from urllib.request import urlopen


CORE_DIR: Path = Path(__file__).resolve().parent
SKILL_DIR: Path = CORE_DIR / "wewrite"
TOOLKIT_DIR: Path = SKILL_DIR / "toolkit"
SCRIPTS_DIR: Path = SKILL_DIR / "scripts"


# Force UTF-8 on stdio. The VCP synchronous-plugin protocol speaks JSON with
# Chinese punctuation and the HTML body emitted by wewrite contains bullets
# (U+2022) and many CJK chars that the default Windows console codec (cp936)
# cannot encode. We must reconfigure before any read/write.
for _stream_name in ("stdin", "stdout", "stderr"):
    _stream = getattr(sys, _stream_name, None)
    if _stream is not None and hasattr(_stream, "reconfigure"):
        try:
            _stream.reconfigure(encoding="utf-8", errors="replace")
        except Exception:
            pass


# Strip inherited HTTP/HTTPS proxy env vars before anything else imports
# `requests` / `urllib`. Rationale:
#   - WeChat Open Platform requires API calls to come from a whitelisted public
#     IP. A LAN proxy (e.g. 127.0.0.1:8800) is either unreachable from this
#     child process or has an outbound IP that is NOT in the whitelist, which
#     causes 40164 errors or socket failures.
#   - VCP's server.js inherits whatever proxy env vars were set in the shell
#     that launched it. On Windows, Cursor/IDE terminals frequently carry stale
#     or malformed (e.g. markdown-wrapped) proxy values that propagate into
#     every spawned plugin subprocess.
#   - Allow an explicit opt-in via WEWRITE_ALLOW_PROXY=1 for advanced users who
#     have a whitelisted upstream proxy.
if os.environ.get("WEWRITE_ALLOW_PROXY", "").lower() not in ("1", "true", "yes"):
    _proxy_vars = (
        "HTTP_PROXY", "HTTPS_PROXY", "ALL_PROXY",
        "http_proxy", "https_proxy", "all_proxy",
    )
    _stripped: list[str] = []
    for _v in _proxy_vars:
        if _v in os.environ:
            _stripped.append(f"{_v}={os.environ[_v]!r}")
            del os.environ[_v]
    os.environ["NO_PROXY"] = "*"
    os.environ["no_proxy"] = "*"
    if _stripped and os.environ.get("DebugMode", "").lower() in ("true", "1"):
        print(f"[WeWriteCore] stripped inherited proxy env: {_stripped}",
              file=sys.stderr, flush=True)


def _split_csv(raw: str | None) -> list[str]:
    if not raw:
        return []
    parts = re.split(r"[,，;；\n]+", raw)
    return [p.strip() for p in parts if p.strip()]


def _env(key: str, default: str | None = None) -> str | None:
    val = os.environ.get(key)
    if val is None or val == "":
        return default
    return val


def _bool_env(key: str, default: bool = False) -> bool:
    val = os.environ.get(key)
    if val is None:
        return default
    return val.strip().lower() in ("1", "true", "yes", "on", "y")


# ---------------------------------------------------------------------------
# Config rendering
# ---------------------------------------------------------------------------

def render_config_yaml() -> Path:
    """Render `wewrite/config.yaml` from VCP env vars.

    Only writes when at least one of the supported env vars is set, OR when
    no config.yaml currently exists (in which case an empty stub is written
    so wewrite's "skip_publish"/"skip_image_gen" auto-degrade kicks in).
    """
    path = SKILL_DIR / "config.yaml"

    appid = _env("WECHAT_APPID")
    secret = _env("WECHAT_SECRET")
    author = _env("WECHAT_AUTHOR") or _env("WEWRITE_AUTHOR")
    theme = _env("WEWRITE_DEFAULT_THEME", "professional-clean")

    lines: list[str] = ["# Auto-generated by Plugin/WeWriteCore/bootstrap.py", ""]
    if appid or secret or author:
        lines.append("wechat:")
        lines.append(f"  appid: \"{appid or ''}\"")
        lines.append(f"  secret: \"{secret or ''}\"")
        if author:
            lines.append(f"  author: \"{author}\"")
        lines.append("")

    lines.append(f"theme: \"{theme}\"")
    lines.append("")

    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def render_style_yaml() -> Path:
    """Render `wewrite/style.yaml` from VCP env vars when set.

    This is needed by the Agent-facing SKILL.md flow (Step 1.3). For pure
    Markdown→HTML and publish use-cases the file is not consulted by
    toolkit code, but we still write a sensible stub so that downstream
    scripts (fetch_hotspots, extract_exemplar, ...) can run later.
    """
    path = SKILL_DIR / "style.yaml"

    def _yaml_str(v: str) -> str:
        return json.dumps(v, ensure_ascii=False)

    def _yaml_list(items: list[str]) -> str:
        if not items:
            return "[]"
        return "[" + ", ".join(_yaml_str(i) for i in items) + "]"

    name = _env("WEWRITE_NAME", "VCP公众号")
    industry = _env("WEWRITE_INDUSTRY", "科技/互联网")
    audience = _env("WEWRITE_TARGET_AUDIENCE", "")
    topics = _split_csv(_env("WEWRITE_TOPICS"))
    tone = _env("WEWRITE_TONE", "专业但不学术，有观点但不偏激")
    voice = _env("WEWRITE_VOICE", "第一人称，像一个懂行的朋友在分享见解")
    word_count = _env("WEWRITE_WORD_COUNT", "1500-2500")
    content_style = _env("WEWRITE_CONTENT_STYLE", "干货")
    persona = _env("WEWRITE_WRITING_PERSONA", "midnight-friend")
    theme = _env("WEWRITE_DEFAULT_THEME", "professional-clean")
    author = _env("WEWRITE_AUTHOR", "")
    cover_style = _env("WEWRITE_COVER_STYLE", "简洁封面，主体明确")
    blacklist_words = _split_csv(_env("WEWRITE_BLACKLIST_WORDS"))
    blacklist_topics = _split_csv(_env("WEWRITE_BLACKLIST_TOPICS"))
    reference_accounts = _split_csv(_env("WEWRITE_REFERENCE_ACCOUNTS"))

    lines: list[str] = [
        "# Auto-generated by Plugin/WeWriteCore/bootstrap.py",
        f"name: {_yaml_str(name)}",
        f"industry: {_yaml_str(industry)}",
    ]
    if audience:
        lines.append(f"target_audience: {_yaml_str(audience)}")

    lines.append("topics:")
    for t in (topics or ["AI/人工智能", "效率工具"]):
        lines.append(f"  - {_yaml_str(t)}")

    lines += [
        f"tone: {_yaml_str(tone)}",
        f"voice: {_yaml_str(voice)}",
        f"word_count: {_yaml_str(word_count)}",
        f"content_style: {_yaml_str(content_style)}",
        f"writing_persona: {_yaml_str(persona)}",
        "blacklist:",
        f"  words: {_yaml_list(blacklist_words)}",
        f"  topics: {_yaml_list(blacklist_topics)}",
        f"reference_accounts: {_yaml_list(reference_accounts)}",
        f"theme: {_yaml_str(theme)}",
        f"cover_style: {_yaml_str(cover_style)}",
    ]
    if author:
        lines.append(f"author: {_yaml_str(author)}")

    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def ensure_runtime() -> dict[str, Path]:
    """Ensure wewrite is ready to be invoked. Returns key paths."""
    if not SKILL_DIR.exists():
        raise RuntimeError(
            f"Embedded wewrite source missing at {SKILL_DIR}. "
            "Re-run the WeWriteCore installation."
        )
    config_path = render_config_yaml()
    style_path = render_style_yaml()

    for sub in ("output", "lessons", "corpus"):
        (SKILL_DIR / sub).mkdir(parents=True, exist_ok=True)

    return {
        "skill_dir": SKILL_DIR,
        "toolkit_dir": TOOLKIT_DIR,
        "scripts_dir": SCRIPTS_DIR,
        "config": config_path,
        "style": style_path,
    }


# ---------------------------------------------------------------------------
# Stdin / stdout helpers (VCP synchronous plugin protocol)
# ---------------------------------------------------------------------------

def read_args() -> dict[str, Any]:
    """Read the JSON arg object that VCP delivers on stdin.

    Tolerates an optional UTF-8 BOM (some shells / VCP test harnesses
    insert one) and leading/trailing whitespace.
    """
    raw = sys.stdin.read()
    if not raw:
        return {}
    if raw.startswith("\ufeff"):
        raw = raw.lstrip("\ufeff")
    raw = raw.strip()
    if not raw:
        return {}
    try:
        data = json.loads(raw)
    except json.JSONDecodeError as e:
        raise ValueError(f"Invalid JSON on stdin: {e}") from e
    if not isinstance(data, dict):
        raise ValueError(f"Expected JSON object on stdin, got {type(data).__name__}")
    return data


def success(result: Any) -> None:
    """Emit a VCP success envelope to stdout and exit."""
    sys.stdout.write(json.dumps({"status": "success", "result": result}, ensure_ascii=False))
    sys.stdout.flush()
    sys.exit(0)


def failure(error: str, *, code: str | None = None, extra: dict | None = None) -> None:
    """Emit a VCP error envelope to stdout and exit."""
    payload: dict[str, Any] = {"status": "error", "error": str(error)}
    if code:
        payload["code"] = code
    if extra:
        payload.update(extra)
    sys.stdout.write(json.dumps(payload, ensure_ascii=False))
    sys.stdout.flush()
    sys.exit(1)


def pick(args: dict[str, Any], *aliases: str, default: Any = None) -> Any:
    """Look up an argument by any of the given aliases (case-insensitive)."""
    if not args:
        return default
    lowered = {str(k).lower(): v for k, v in args.items()}
    for alias in aliases:
        v = args.get(alias)
        if v not in (None, ""):
            return v
        v = lowered.get(alias.lower())
        if v not in (None, ""):
            return v
    return default


# ---------------------------------------------------------------------------
# Markdown input materialization
# ---------------------------------------------------------------------------

def materialize_markdown(value: str, *, prefix: str = "wewrite-") -> Path:
    """Turn a string OR a path into a real file on disk.

    Accepts:
      - Raw markdown content (heuristic: contains newlines, '#', or no path-like chars).
      - An absolute or relative filesystem path.
      - A `file://` URL.
    """
    if not value:
        raise ValueError("Empty markdown input")

    # file:// URL → local path
    if value.startswith("file://"):
        parsed = urlparse(value)
        local = Path(unquote(parsed.path.lstrip("/")) if os.name == "nt" else unquote(parsed.path))
        if local.exists() and local.is_file():
            return local
        raise FileNotFoundError(value)

    candidate = Path(value)
    looks_like_path = (
        len(value) < 1024
        and "\n" not in value
        and ("/" in value or "\\" in value or value.lower().endswith((".md", ".markdown", ".txt")))
    )
    if looks_like_path and candidate.exists() and candidate.is_file():
        return candidate

    # Treat as raw markdown content → write to temp file under wewrite/output
    out_dir = SKILL_DIR / "output"
    out_dir.mkdir(parents=True, exist_ok=True)
    fd, tmp_path = tempfile.mkstemp(prefix=prefix, suffix=".md", dir=str(out_dir))
    with os.fdopen(fd, "w", encoding="utf-8") as f:
        f.write(value)
    return Path(tmp_path)


# ---------------------------------------------------------------------------
# Cover-image input (supports VCP hyper-stack-trace)
# ---------------------------------------------------------------------------

def _has_pw_segment(parsed_path: str) -> bool:
    return any(part.startswith("pw=") for part in parsed_path.split("/") if part)


def is_local_image_server_url(value: str) -> bool:
    """Return true for VCP image-server URLs that can be resolved locally."""
    parsed = urlparse(value)
    if parsed.scheme not in ("http", "https"):
        return False

    parts = [part for part in parsed.path.split("/") if part]
    if "images" not in parts:
        return False

    host = (parsed.hostname or "").lower()
    local_hosts = {"localhost", "127.0.0.1", "::1"}
    return host in local_hosts or _has_pw_segment(parsed.path)


def local_image_server_path(value: str) -> Path | None:
    """Map a VCP `/images/...` URL back to PROJECT_BASE_PATH/image/..."""
    if not is_local_image_server_url(value):
        return None

    project_base = os.environ.get("PROJECT_BASE_PATH", "").strip()
    if not project_base:
        return None

    parsed = urlparse(value)
    parts = [unquote(part) for part in parsed.path.split("/") if part]
    try:
        images_idx = parts.index("images")
    except ValueError:
        return None

    relative_parts = parts[images_idx + 1:]
    if not relative_parts:
        return None

    candidate = Path(project_base) / "image" / Path(*relative_parts)
    if candidate.exists() and candidate.is_file():
        return candidate
    return None


def materialize_image(value: str, *, param_name: str) -> Path:
    """Resolve an image URL/path/data URI to a real local file.

    Supports:
      - Local path (absolute or relative)
      - file:// URL (raises FILE_NOT_FOUND_LOCALLY for VCP hyper-stack-trace
        if the file does not exist on this node)
      - http(s):// URL (downloaded)
      - data:image/...;base64,... URI

    Raises a structured exception that the plugin entry should catch and
    forward to VCP via `emit_file_not_found`.
    """
    if not value:
        raise ValueError(f"{param_name}: empty value")

    # data URI
    m = re.match(r"^data:(image/[^;]+);base64,(.*)$", value, re.IGNORECASE | re.DOTALL)
    if m:
        ext = (m.group(1).split("/", 1)[1] or "png").split("+", 1)[0]
        raw = base64.b64decode(m.group(2))
        tmp = Path(tempfile.mkstemp(prefix="wewrite-img-", suffix=f".{ext}", dir=str(SKILL_DIR / "output"))[1])
        tmp.write_bytes(raw)
        return tmp

    # file:// URL
    if value.startswith("file://"):
        parsed = urlparse(value)
        raw_path = unquote(parsed.path)
        if os.name == "nt" and raw_path.startswith("/") and re.match(r"^/[A-Za-z]:", raw_path):
            raw_path = raw_path[1:]
        local = Path(raw_path)
        if local.exists() and local.is_file():
            return local
        err = FileNotFoundError(f"{param_name}: local file not found, requires remote fetch")
        err.code = "FILE_NOT_FOUND_LOCALLY"  # type: ignore[attr-defined]
        err.fileUrl = value  # type: ignore[attr-defined]
        err.failedParameter = param_name  # type: ignore[attr-defined]
        raise err

    # http(s)://
    if value.startswith(("http://", "https://")):
        local_server_path = local_image_server_path(value)
        if local_server_path is not None:
            return local_server_path
        if is_local_image_server_url(value):
            raise FileNotFoundError(f"{param_name}: file not found: {value}")

        with urlopen(value, timeout=60) as resp:
            data = resp.read()
            ct = resp.headers.get_content_type() or "image/png"
            ext = ct.split("/", 1)[1].split(";", 1)[0] or "png"
        tmp = Path(tempfile.mkstemp(prefix="wewrite-img-", suffix=f".{ext}", dir=str(SKILL_DIR / "output"))[1])
        tmp.write_bytes(data)
        return tmp

    # Plain path
    local = Path(value)
    if local.exists() and local.is_file():
        return local

    project_base = os.environ.get("PROJECT_BASE_PATH", "").strip()
    if project_base and not local.is_absolute():
        project_candidate = Path(project_base) / local
        if project_candidate.exists() and project_candidate.is_file():
            return project_candidate

    raise FileNotFoundError(f"{param_name}: file not found: {value}")


def emit_file_not_found(err: BaseException) -> None:
    """Emit the VCP `FILE_NOT_FOUND_LOCALLY` envelope and exit."""
    payload = {
        "status": "error",
        "code": "FILE_NOT_FOUND_LOCALLY",
        "error": str(err),
        "fileUrl": getattr(err, "fileUrl", ""),
    }
    failed_param = getattr(err, "failedParameter", None)
    if failed_param:
        payload["failedParameter"] = failed_param
    sys.stdout.write(json.dumps(payload, ensure_ascii=False))
    sys.stdout.flush()
    sys.exit(1)


# ---------------------------------------------------------------------------
# Subprocess helpers
# ---------------------------------------------------------------------------

def run_python(script: Path, args: Iterable[str], *, cwd: Path | None = None,
               timeout: int = 600) -> subprocess.CompletedProcess:
    """Run a wewrite python script with sane defaults."""
    cmd = [sys.executable, str(script), *args]
    env = os.environ.copy()
    py_path = os.pathsep.join(
        p for p in (str(TOOLKIT_DIR), str(SCRIPTS_DIR), env.get("PYTHONPATH", "")) if p
    )
    env["PYTHONPATH"] = py_path
    env.setdefault("PYTHONIOENCODING", "utf-8")
    return subprocess.run(
        cmd,
        cwd=str(cwd) if cwd else str(SKILL_DIR),
        env=env,
        capture_output=True,
        text=True,
        encoding="utf-8",
        timeout=timeout,
    )


def inject_toolkit_path() -> None:
    """Add wewrite toolkit/scripts dirs to sys.path so `import converter`,
    `import theme`, etc. work directly inside the current process."""
    for d in (TOOLKIT_DIR, SCRIPTS_DIR):
        s = str(d)
        if s not in sys.path:
            sys.path.insert(0, s)


__all__ = [
    "CORE_DIR",
    "SKILL_DIR",
    "TOOLKIT_DIR",
    "SCRIPTS_DIR",
    "ensure_runtime",
    "render_config_yaml",
    "render_style_yaml",
    "read_args",
    "success",
    "failure",
    "pick",
    "materialize_markdown",
    "materialize_image",
    "is_local_image_server_url",
    "local_image_server_path",
    "emit_file_not_found",
    "run_python",
    "inject_toolkit_path",
]
